# This is the base folder for storing the Matrix Market files
path: ./datasets

graph500:
  generators:
    graph500:
      scale:
        - 20
        - 20
        - 21
        - 21
      edge_factor:
        - 8
        - 32
        - 8
        - 16

small_diameter:
  suite_sparse_matrix_list:
    # - GAP/GAP-twitter
    # - GAP/GAP-web
    # - LAW/webbase-2001
    # - SNAP/twitter7
    - LAW/hollywood-2009
    - SNAP/soc-LiveJournal1
    - Gleich/wikipedia-20070206
    - SNAP/roadNet-CA

large_diameter:
  suite_sparse_matrix_list:
    - GAP/GAP-road
    - DIMACS10/europe_osm
    - DIMACS10/rgg_n_2_22_s0
    - DIMACS10/rgg_n_2_24_s0


